[package]
name = "eflomal-wasm"
version = "0.1.0"
edition = "2021"
description.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
eflomal-core = { path = "../eflomal-core" }
wasm-bindgen = "0.2"
