[package]
name = "eflomal-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
eflomal-core = { path = "../eflomal-core" }
wasm-bindgen = "0.2"

[profile.release]
# Recommended for Workers/Electron wasm
opt-level = "z"
lto = true
codegen-units = 1